### ISSUE TITLE
curl / certification problems on Windows

### ISSUE THREAD

**Issue by rossmounce** [wcornwell/taxonlookup#28] opened 2016-07-29 13:50 UTC
I've been trying to help our plant records officer at the Cambridge University Botanic Garden to install `taxonlookup` on his Windows 7 work machine (apologies in advance, this won't be a very detailed or reproducible issue report given the difficult circumstances - not my machine!).

We had significant problems getting `taxonlookup` installed mainly I think due to problems with SSL certificates and/or `curl` or `Rcurl`. I ended up installing all the required dependencies from local binary or source packages because of this impediment. I believe I had `taxonlookup` successfully installed (from local source) but was met with this error message:

```
lookup_table(c("Pinus ponderosa","Quercus agrifolia"),by_species=TRUE)
Error: key 'traitecoevo/taxonlookup' ('objects') not found, with error: Problem with the SSL CA cert (path? access rights?)
```

Is there anyway to get around this? 
Why does the package need SSL CA cert anyway once installed? 
Isn't the lookup done entirely offline against the .csv data ? 

I know this is probably not really an issue with `taxonlookup` per se but if you had any clue what might be causing it that would be really helpful. Getting the user off Windows is unfortunately not an option.

**Comment by wcornwell** [comment] 2016-07-31 04:42
Hi Ross, 

> Isn't the lookup done entirely offline against the .csv data ?

Yes, but first it has to download the .csv, and that's where the error is, so it's something about R not being able to talk to websites on this computer, probably because `curl` is not finding the right libraries.  basically taxonlookup uses [httr](https://github.com/hadley/httr) which uses [curl](https://github.com/jeroenooms/curl) to talk to github in order to download the data.  That only has to happen once on each machine and then everything else is local.  

I don't know anything about windows, but my approach would be to try the hello world section of the readme here: https://github.com/jeroenooms/curl and see if that works?  

I'll try a few windows machines at work and see if I can reproduce this behavior, but I think this sounds pretty specific.

**Comment by rossmounce** [comment] 2016-08-01 08:05
Ahhh... that would explain it.

Can the .csv not just be included in the source of the package? It's not that large.
I'll have look to see if I can fix it for him next week. You're right it might be something quite specific, I haven't tested on other Windows boxes.

Thanks

**Comment by wcornwell** [comment] 2016-08-02 03:13
The versioning of the data won't work if we include it in the package.  @richfitz has strong opinions about this.  

I've checked on some windows boxes here and it works fine--I can't replicate the error, so it's got to be something specific about curl and the libraries that it calls on that machine.  

It's weird that `devtools::install_github` would work, but `http::GET` wouldn't work, but clearly I don't understand this deeply enough...

**Comment by wcornwell** [comment] 2016-08-10 02:21
Closing this, as I think it's really a Windows-[Curl](https://github.com/jeroenooms/curl) issue,

**Closed as completed by wcornwell** 2016-08-10 02:21 UTC
